sudo: required
services:
- docker
language: python
python:
- 3.6
install:
- bash ./travis-ci/docker_build.sh
script:
- bash ./travis-ci/docker_test.sh
env:
  global:
  - CI_IMAGE_NAME=base
  - CI_SO=alpine
  - matrix:
    - CI_SO_VER=3.4 CI_JAVA_MAJOR=8  CI_JAVA_MINOR=112  CI_JAVA_BUILD=15  CI_PY_VER=2.7  CI_PY_BUILD=12-r0  CI_PIP_VER=8.1.2-r0
notifications:
  slack: 
    secure: SL9ZOBdNUyYNfMEZ7YEHIhYkxMyGMWnzMDf5HcU4+cKJdqGbUC4c78hbBLi/bCN6D8ftyDiitU1/NTEXRjXBxbWVFSavQ5MjjN5PYt38u4a50aEHYds8VyubQ+DqPDdYl/wvQGCh+L5n6RNoB8WwGkbYxHjbTG33CCvpuoIpLzgvk0XMEdJkRxu1i+hq3uZsexYN8b8QNcegbkGvfzWbxU0JTJU0u8nRzn2uNAsf1FiuDX5XTXz3WKMuN0DZulJ4PTmZw4ccNMSjIAggqZ9EwqQC9ab9jzbcQn1oivNc0Wo65EfJbL4IaB5e+Y7Fw3/EXASM6xQNeRKzNsq7eZNZHLmj+UKzJva4WvdSFNqxpRQL0QDr0AVWbAPU4hRMI7d5n2C7KgPcb8Kx4MCoRVl7t5vRjL1F8Vae7hVg3BT5cSOyrIdQbTClw69qH4lqrGFBmCvAB1MBMwFn3uCr0IVP85qKXSuCS6cbYyzk7Nke//tZt0jaEQep082xPpdQgihuYTSUAnZvDu3qAymCRTPPumGZiWhNaicMq+a/mcakMrTmA8N7tY0srwC8TGUCaW4Itgn0ILZcBgnBx5SnxTKSdo9bzTh8yETIyHtnR7Jhsu+gkizuQ03DNT47WU3Fi7hYweVomsXmxScx9WtKzcYYadCzLmR+TmFkKRyRMDt3t1c=
branches:
  only:
  - master
before_deploy: tar -zcvf Dockerfiles.tar.gz ./Dockerfiles
deploy:
  provider: releases
  api_key:
    secure: "UnmtAoi7zk7ydpr+YD0Oxty/m9/n/UOIxutl+vO9n3HkgKGTwwnhBkz08T0wJvHzj6JTgXTpxRtWiqQ3txPEqXu1a8Om6blavR6R8A7IPh2bmU3lwzKAqYIvSQyGX9jYHhi273+uC+sin4yUpq8r7S6Da7kngpfvVwV1c40tqDR8pIvfd7L4NOjtLB07MAXmeAxRvVQ6f/4hpLsb7ts9ZB+EPWQwtBqBrFx4tn67SrXGdtthu11FJ6t2fmSscrgFBEnSHAEtq4arGb/joOBMr3k+Mhqa1J8EUlmGZGmo3KnDbxqKNcMcVbE9IpqWRIGtJv6mc3bwG8kRzWuIxUmI4NOy4xF+RgapBIiNvE2VUJ7K3OYDu/1D5sEpvHJXds5MKdm7qk9D6UfR+tWC5EaETYVg4cpiH/VzcD4o9qPEaLcWQnr2ipfIXxs/orFNrV5NGjB9hq1e+gmOJM1gDN3LZWsrarLEevr5PDVmPcGmq6dIeq6noPWlkdMAM7rXoZLSQEP69r2R7+cYdXxON22wrpxvhyYD7DzTaeNwZxqa8YuZIZhOBY85PgymeK30qwDRe50MiXEDxVAlCtMjH2qkcm1XAAO33G/WQ2n/pQrYi8ufsWOHW4U63q50JF0V5pAWfrfYNAcWzfgtrSdym96ChTm4DIu9GF1jzXleNhjmn/Q="
  file: "./Dockerfiles.tar.gz"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- echo "deployed1"
- echo "deployed2"
